image: gradle

stages:
    - test
    - package

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/core/.gradle
  PROJECT_NAME: "atteste"

junit:
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - cd core
    - gradle test

jar:
  stage: package
  script:
    - cd core
    - sed -i "s/{VERSION}/$CI_COMMIT_REF_NAME/g" build.gradle
    - gradle bootJar
  after_script:
    - mkdir $PROJECT_NAME
    - mv $PROJECT_NAME.service $PROJECT_NAME/
    - mv $PROJECT_NAME.conf $PROJECT_NAME/
    - mv build/libs/$PROJECT_NAME-*.jar $PROJECT_NAME/
    - cd $PROJECT_NAME
    - ln -s $PROJECT_NAME-*.jar $PROJECT_NAME.jar
    - cd ..
  artifacts:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $PROJECT_NAME/*
