image: gradle

stages:
    - test
    - package
    
variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  PROJECT_NAME: "atteste"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/caches

junit:
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - gradle test
  after_script:
    - cat build/reports/jacoco/test/html/index.html

jar:
  stage: package
  script:
    - sed -i "s/{VERSION}/$CI_COMMIT_REF_NAME/g" build.gradle
    - gradle bootJar
  after_script:
    - mkdir $PROJECT_NAME
    - mv $PROJECT_NAME.service $PROJECT_NAME/
    - mv $PROJECT_NAME.conf $PROJECT_NAME/
    - mv build/libs/$PROJECT_NAME-*.jar $PROJECT_NAME/
    - cd $PROJECT_NAME
    - ln -s $PROJECT_NAME-*.jar $PROJECT_NAME.jar
    - cd ..
  artifacts:
    name: "$PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $PROJECT_NAME/*
