image: gradle

stages:
    - test
    - package

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  PROJECT_NAME: "centralcert"


junit:
  stage: test
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - gradle test

sonarqube:
  stage: test
  only:
    - develop # SonarQube Community is limited to one branch. 'develop' is the most relevant.
  script:
    - gradle sonar -Dsonar.host.url=https://sonarqube.libriciel.fr -D sonar.login=$SONAR_TOKEN

jar:
  stage: package
  script:
    - sed -i "s/{VERSION}/$CI_COMMIT_REF_NAME/g" build.gradle
    - gradle bootJar
