version: '3.3'
services:
  app:
    image: atteste
    ports:
      - 8080:8080
      
  db:
    image: postgres:9.4
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA : /var/lib/postgresql/data
    volumes:
      - /projects/own/docker_php/pgdata:/var/lib/postgresql/data