version: '3.2'
services:
  reverse:
    image: nginx:alpine
    depends_on:
      - core
      - frontend
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    build: ../frontend
    depends_on:
      - core
    ports:
      - 4200
    volumes:
      - /usr/src/app
    command: "ng serve --host 0.0.0.0 --disable-host-check"

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    tty: true
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - DB_ADDR=db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_IMPORT=/tmp/keycloak.json
    volumes:
      - ./keycloak/keycloak.json:/tmp/keycloak.json
    ports:
      - 9090:8080
    depends_on:
      - db

  core:
    build: ../core
    depends_on:
      - db

  db:
    build: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - DB_TO_CREATE=atteste,keycloak
    command: postgres -c max_connections=300 -c log_min_messages=LOG
